spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zjl?serverTimezone=UTC
    username: root
    password: 8825
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl